# Generated by Django 2.2.4 on 2019-09-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(max_length=300)),
                ('is_publish', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=130)),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
