# Generated by Django 2.2.4 on 2019-09-29 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.School'),
        ),
    ]
