# Generated by Django 2.2.4 on 2019-10-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20191007_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feetype',
            name='fee_type',
            field=models.CharField(choices=[('GeneralFee', 'GeneralFee'), ('Hostel', 'Hostel'), ('Transport', 'Transport')], max_length=100),
        ),
    ]
