# Generated by Django 2.2.4 on 2019-10-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20191007_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feetype',
            name='class1',
            field=models.CharField(default='Shs 0.0', max_length=100),
        ),
        migrations.AlterField(
            model_name='feetype',
            name='class2',
            field=models.CharField(default='Shs 0.0', max_length=100),
        ),
        migrations.AlterField(
            model_name='feetype',
            name='class3',
            field=models.CharField(default='Shs 0.0', max_length=100),
        ),
    ]
