# Generated by Django 2.2.4 on 2019-09-29 13:30

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('schools', '0003_feedback_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='dynamic_tags',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='dynamic_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.RemoveField(
            model_name='smstemplate',
            name='dynamic_tags',
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='dynamic_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
