# Generated by Django 2.2.4 on 2019-10-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20191008_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='paid_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=100),
        ),
    ]
