# Generated by Django 2.2.4 on 2019-09-30 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20190929_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='coming_from',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='reason_to_meet',
        ),
        migrations.AddField(
            model_name='visitor',
            name='visitor_purpose',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Purpose'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='note',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='to_meet_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='to_meet_user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Role'),
        ),
    ]
