# Generated by Django 2.2.4 on 2019-09-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_auto_20190930_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='postal_Attachment',
            field=models.FileField(default=1, upload_to='attachments/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Receive',
        ),
    ]
