# Generated by Django 2.2.4 on 2019-10-08 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_auto_20191008_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='fee_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.FeeType'),
        ),
    ]
