# Generated by Django 2.2.4 on 2019-10-08 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_auto_20191008_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feetype',
            old_name='class1',
            new_name='Class_Amount',
        ),
        migrations.RemoveField(
            model_name='feetype',
            name='class2',
        ),
        migrations.RemoveField(
            model_name='feetype',
            name='class3',
        ),
        migrations.AddField(
            model_name='feetype',
            name='Class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Classroom'),
        ),
    ]
