# Generated by Django 2.2.4 on 2019-09-30 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_auto_20190930_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_Title', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('from_Title', models.CharField(max_length=100)),
                ('receive_date', models.DateField(max_length=100)),
                ('note', models.TextField(max_length=100)),
                ('postal_Attachment', models.FileField(upload_to='attachments/')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.School')),
            ],
        ),
    ]
