# Generated by Django 2.2.4 on 2019-09-30 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_receive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='leave_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.Leave'),
        ),
    ]
