# Generated by Django 2.2.4 on 2019-09-30 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_auto_20190930_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(max_length=130)),
                ('section', models.CharField(max_length=130)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('activity', models.TextField(max_length=130)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ('classroom',),
                'verbose_name_plural': 'classrooms',
                'ordering': ('classroom',),
            },
        ),
    ]
