# Generated by Django 2.2.4 on 2019-10-11 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_auto_20191011_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='gross_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_number',
        ),
    ]
