# Generated by Django 2.2.4 on 2019-09-30 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={},
        ),
        migrations.AlterField(
            model_name='activity',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.Classroom'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.Section'),
        ),
    ]
