# Generated by Django 2.2.4 on 2019-10-11 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_auto_20191011_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feetype',
            name='Class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Classroom'),
        ),
        migrations.AlterField(
            model_name='feetype',
            name='Class_Amount',
            field=models.CharField(blank=True, default='Shs 0.0', max_length=100, null=True),
        ),
    ]
