# Generated by Django 2.2.4 on 2019-09-30 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_auto_20190930_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('border_color', models.CharField(max_length=130)),
                ('top_background', models.CharField(max_length=130)),
                ('card_school_name', models.CharField(max_length=130)),
                ('school_name_font_size', models.CharField(max_length=130)),
                ('school_name_color', models.CharField(max_length=130)),
                ('school_address', models.CharField(max_length=130)),
                ('school_address_color', models.CharField(max_length=130)),
                ('admit_card_font_size', models.CharField(max_length=130)),
                ('admit_card_color', models.CharField(max_length=130)),
                ('admit_card_background', models.CharField(max_length=130)),
                ('title_font_size', models.CharField(max_length=130)),
                ('title_color', models.CharField(max_length=130)),
                ('value_font_size', models.CharField(max_length=130)),
                ('value_color', models.CharField(max_length=130)),
                ('exam_font_size', models.CharField(max_length=130)),
                ('exam_color', models.CharField(max_length=130)),
                ('subject_font_size', models.CharField(max_length=130)),
                ('subject_color', models.CharField(max_length=130)),
                ('bottom_signature', models.CharField(max_length=130)),
                ('signature_background', models.CharField(max_length=130)),
                ('signature_color', models.CharField(max_length=130)),
                ('signature_align', models.CharField(max_length=130)),
                ('admit_card_logo', models.FileField(null=True, upload_to='card/')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School')),
            ],
        ),
    ]
