# Generated by Django 2.2.4 on 2019-10-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_auto_20191011_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Bank_Name',
            field=models.CharField(blank=True, default='Shs 0.0', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='Cheque_Number',
            field=models.CharField(blank=True, default='Shs 0.0', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='Payment_Method',
            field=models.CharField(blank=True, default='Shs 0.0', max_length=100, null=True),
        ),
    ]
