# Generated by Django 2.2.4 on 2019-10-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_auto_20191011_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Payment_Method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque')], max_length=100, null=True),
        ),
    ]
