# Generated by Django 2.2.4 on 2019-10-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_complain_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='action_date',
            field=models.DateField(null=True),
        ),
    ]
