# Generated by Django 2.2.4 on 2019-10-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_auto_20191011_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='Bank_Name',
            field=models.CharField(blank=True, default='bank name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='Cheque_Number',
            field=models.CharField(blank=True, default='cheque number', max_length=100, null=True),
        ),
    ]
