# Generated by Django 2.2.4 on 2019-10-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_auto_20191014_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque')], max_length=100),
        ),
    ]
