# Generated by Django 2.2.4 on 2019-10-01 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_auto_20191001_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manageuser',
            old_name='school_name',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='manageuser',
            old_name='user_details',
            new_name='user',
        ),
    ]
