# Generated by Django 2.2.4 on 2019-10-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_auto_20191014_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarygrade',
            name='gross_salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salarygrade',
            name='net_salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salarygrade',
            name='total_allowance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salarygrade',
            name='total_deduction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
