# Generated by Django 2.2.4 on 2019-10-17 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_salarypayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarypayment',
            name='employee',
        ),
    ]
