# Generated by Django 2.2.4 on 2019-10-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_auto_20191002_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routine',
            options={'ordering': ('day', 'start_time'), 'verbose_name': 'Routine', 'verbose_name_plural': 'Routine'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='month',
            field=models.CharField(max_length=100),
        ),
    ]
