# Generated by Django 2.2.4 on 2019-10-18 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0019_auto_20191018_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarygrade',
            name='Bonus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salarygrade',
            name='Expenditure_Head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.ExpenditureHead'),
        ),
        migrations.AddField(
            model_name='salarygrade',
            name='Month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salarygrade',
            name='Payment_Method',
            field=models.CharField(blank=True, choices=[('Cheque', 'Cheque'), ('MobileMoney', 'MobileMoney'), ('Cash', 'Cash')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salarygrade',
            name='Penalty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salarygrade',
            name='over_time_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salarygrade',
            name='over_time_total_hour',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
