# Generated by Django 2.2.4 on 2019-10-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0020_auto_20191018_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarygrade',
            name='Bank_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salarygrade',
            name='Cheque_Number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
