# Generated by Django 2.2.4 on 2019-10-22 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0021_auto_20191020_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarygrade',
            name='payee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Employee'),
        ),
    ]
