# Generated by Django 2.2.4 on 2019-10-22 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0022_salarygrade_payee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarygrade',
            name='payee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
