# Generated by Django 2.2.4 on 2019-10-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0023_auto_20191022_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySalaryPaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('grade_name', models.CharField(max_length=100)),
                ('basic_salary', models.CharField(max_length=100)),
                ('house_rent', models.CharField(max_length=100)),
                ('transport_allowance', models.CharField(max_length=100)),
                ('medical_allowance', models.CharField(max_length=100)),
                ('over_time_hourly_pay', models.CharField(max_length=100)),
                ('provident_fund', models.CharField(max_length=100)),
                ('hourly_rate', models.CharField(max_length=100)),
                ('total_allowance', models.CharField(max_length=100)),
                ('total_deduction', models.CharField(max_length=100)),
                ('gross_salary', models.CharField(max_length=100)),
                ('net_salary', models.CharField(max_length=100)),
                ('over_time_total_hour', models.CharField(max_length=100)),
                ('over_time_amount', models.CharField(max_length=100)),
                ('Bonus', models.CharField(max_length=100)),
                ('Penalty', models.CharField(max_length=100)),
                ('Month', models.CharField(max_length=100)),
                ('Payment_Method', models.CharField(max_length=100)),
                ('Expenditure_Head', models.CharField(max_length=100)),
            ],
        ),
    ]
