# Generated by Django 2.2.4 on 2019-10-04 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0023_auto_20191004_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='subject',
        ),
    ]
