# Generated by Django 2.2.4 on 2019-10-04 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0024_remove_section_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Student'),
        ),
    ]
