# Generated by Django 2.2.4 on 2019-10-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0024_monthlysalarypaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalarypaid',
            name='Bank_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='monthlysalarypaid',
            name='Cheque_Number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='monthlysalarypaid',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
