# Generated by Django 2.2.4 on 2019-10-24 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0024_monthlysalarypaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='searchPaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Searchemployee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Employee')),
                ('Searchrole', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Role')),
                ('Searchschool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.School')),
            ],
        ),
    ]
