# Generated by Django 2.2.4 on 2019-10-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0025_searchpaymenthistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='searchPaymentHistory',
        ),
    ]
