# Generated by Django 2.2.4 on 2019-10-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0025_mark_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routine',
            options={},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='classroom',
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='leave_Type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feetype',
            name='fee_type',
            field=models.CharField(choices=[('General Fee', 'General Fee'), ('Hostel', 'Hostel'), ('Transport', 'Transport')], max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='fee_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='gross_amount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='month',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='routine',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='section',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='routine',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='subject_name',
            field=models.CharField(max_length=130),
        ),
    ]
