# Generated by Django 2.2.4 on 2019-10-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0028_monthlysalarypaid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date',
            field=models.DateField(auto_now_add=True, default='2019-10-10'),
            preserve_default=False,
        ),
    ]
