# Generated by Django 2.2.4 on 2019-10-29 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0030_academicyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='date',
        ),
        migrations.DeleteModel(
            name='AcademicYear',
        ),
    ]
