# Generated by Django 2.2.4 on 2019-10-29 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0031_auto_20191029_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarygrade',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Year'),
        ),
    ]
