# Generated by Django 2.2.4 on 2019-10-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0032_salarygrade_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalarypaid',
            name='academic_year',
            field=models.CharField(default='2017/2018', max_length=100),
            preserve_default=False,
        ),
    ]
