# Generated by Django 2.2.4 on 2019-11-06 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0034_auto_20191106_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysalarypaid',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Year'),
        ),
    ]
