# Generated by Django 2.2.4 on 2019-11-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0037_student_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='Bank_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='Cheque_Number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
