# Generated by Django 2.2.4 on 2019-11-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0038_auto_20191108_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenditure',
            name='expenditure_method',
        ),
        migrations.AddField(
            model_name='expenditure',
            name='Bank_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='Cheque_Number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque')], default='expenditure', max_length=100),
            preserve_default=False,
        ),
    ]
