# Generated by Django 2.2.4 on 2019-11-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0039_auto_20191109_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feetype',
            name='Class_Amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
