# Generated by Django 2.2.4 on 2019-11-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0040_auto_20191109_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Bank_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Cheque_Number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
